- name: JarFileDirectory
  type: string
  default: ''

- name: JarFileName
  type: string
  default: ''

steps:
- task: PowerShell@2
  displayName: 'Extracting onnxruntime jar file'
  inputs:
    targetType: 'inline'
    script: |
      $original_jar_file_directory = "${{ parameters.JarFileDirectory }}"
      $original_jar_file_name="${{ parameters.JarFileName }}"

      $original_jar_file_full_path = "$original_jar_file_directory\$original_jar_file_name"

      $extracted_file_directory = "$original_jar_file_directory\jar_extracted_full_files"
      Write-Host "Extracting the jar file..."
      & 7z x $original_jar_file_full_path -o"$extracted_file_directory"
      Write-Host "Extracted file directory: $extracted_file_directory"

      Rename-Item "$original_jar_file_full_path" "$original_jar_file_full_path.original"

      $testing_string = "Hello World"
      $testing_file_path = "$extracted_file_directory\testing.txt"
      Out-File -FilePath $testing_file_path -InputObject $testing_string -NoNewline -Encoding ascii
    workingDirectory: '$(Build.BinariesDirectory)'

- template: win-esrp-dll.yml
    parameters:
      FolderPath: '${{ parameters.JarFileDirectory }}\jar_extracted_full_files'
      DisplayName: 'ESRP - Sign C# dlls'

- task: PowerShell@2
  displayName: 'Packing onnxruntime jar file'
  inputs:
    targetType: 'inline'
    script: |
      $original_jar_file_directory = "${{ parameters.JarFileDirectory }}"
      $original_jar_file_name="${{ parameters.JarFileName }}"
      $original_jar_file_full_path = "$original_jar_file_directory\$original_jar_file_name"
      $extracted_file_directory = "$original_jar_file_directory\jar_extracted_full_files"

      Write-Host "Repacking the jar file..."
      & 7z a "$original_jar_file_full_path" "$extracted_file_directory\*"
      Write-Host "Repacked the jar file."

      Remove-Item -Path "$extracted_file_directory" -Recurse -Force
      Remove-Item -Path "$original_jar_file_full_path.original" -Force
      Write-Host "Removed the extracted files and the original jar file."

    workingDirectory: '$(Build.BinariesDirectory)'
